# version: 2.1
# orbs:
#   node: circleci/node@5.0.2
#   aws-cli: circleci/aws-cli@3.0.0
# jobs:
#   build:
#     docker:
#       - image: "cimg/base:stable"
#     steps:
#       - node/install
#       - checkout
#       - aws-cli/setup
#       - run:
#           name: Front-End Install
#           command: |
#             npm run frontend:install
#       - run:
#           name: Back-End Install
#           command: |
#             npm run backend:install
#       - run:
#           name: Front-End Build
#           command: |
#             npm run frontend:build
#       - run:
#           name: Back-End Build
#           command: |
#             npm run backend:build
#       - run:
#           name: Deploy App
#           command: |
#             npm run frontend:deploy

version: 2.1
orbs:
  node: circleci/node@5.0.2
  aws-cli: circleci/aws-cli@3.0.0
jobs:
  frontend:
    executor: node/default
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{checksum "package.json"}}
            - v1-dependencies-
      - run:
          name: install dependencies Frontend
          command: npm run frontend:install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{checksum "package.json"}}
      - run:
          name: Build Frontend
          command: npm run frontend:build
      - aws-cli/install
    - run:
        name: Deploy Frontend
        command: npm run frontend:deploy
workflows:
  build_and_deploy:
    jobs:
      - frontend
